name: Run Express Server on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker buildx build -t backend ./backend

      - name: Stop old container if running
        run: docker stop backend || true && docker rm backend || true

      - name: Run new container
        run: docker run -d -p 3000:8080 --name backend backend